#ifndef DXNA_ERRORCODE_HPP
#define DXNA_ERRORCODE_HPP

namespace dxna {
	enum class ErrorCode {
		NONE,
		ARGUMENT_IS_NULL,
		ARGUMENT_IS_SMALLER,
		ARGUMENT_OUT_OF_RANGE,
		ARGUMENT_IS_LOWER,

		STD_VECTOR_IS_EMPTY
	};
}

#endif